export type EditableText = Record<string, string>;

export type SiteContent = {
  home: EditableText;
  invite: EditableText;
  bachelor: EditableText;
  bachelorette: EditableText;
};

export const DEFAULT_SITE_CONTENT: SiteContent = {
  home: {
    saveTheDate: "SAVE",
    theDate: "THE DATE",
    detailsLead: "TO CELEBRATE THE\nWEDDING OF",
    coupleNames: "AMBER &\nALEX",
    detailsMeta: "JUNE 26TH, 2027\nLOS ANGELES, CALIFORNIA\nFORMAL INVITATION TO FOLLOW",
    shareAddressLabel: "Share mailing address",
    closeLabel: "Close",
    addressDialogTitle: "Share your mailing address",
    fullNamePlaceholder: "Full name",
    streetPlaceholder: "Street address",
    cityPlaceholder: "City",
    statePlaceholder: "State",
    zipPlaceholder: "ZIP",
    saveAddressLabel: "Save address",
  },
  invite: {
    countdownTarget: "2027-06-26T17:00:00-07:00",
    countdownDaysLabel: "days",
    countdownHoursLabel: "hours",
    countdownMinutesLabel: "minutes",
    countdownSecondsLabel: "seconds",
    heroTopLeft: "AA / 2027",
    heroTopRight: "Los Angeles, California",
    heroKicker: "The wedding celebration of",
    heroNames: "Amber & Alex",
    heroDate: "Saturday · June 26 · 2027",
    heroStamp: "Save\nthe\ndate",
    heroFormalLabel: "Formal invitation",
    heroScrollLabel: "Scroll to explore ↓",
    countdownLabel: "Counting down to forever",
    countdownHeading: "See you in the summer.",
    invitationLabel: "Formal invitation",
    invitationHeading: "Together with their families, Amber and Alex invite you to celebrate their marriage.",
    invitationCopy: "We cannot imagine this day without the people who have shaped our story. Please join us for an evening of dinner, dancing, and all the people we love most.",
    invitationSignoff: "With love, A + A",
    ceremonyImageAlt: "St. Monica Catholic Church in Santa Monica",
    ceremonyImageUrl: "https://stmonica.net/images/banners/6328-31AA-3220244994-O.66b05d.jpg",
    ceremonyImageLabel: "01 / The ceremony",
    ceremonyLabel: "Ceremony",
    ceremonyVenue: "St. Monica Catholic Church",
    ceremonyTime: "1:00 PM",
    ceremonyStreet: "725 California Avenue",
    ceremonyCity: "Santa Monica, CA 90403",
    ceremonyMapLabel: "View directions ↗",
    ceremonyMapUrl: "https://www.google.com/maps/search/?api=1&query=St.+Monica+Catholic+Community+725+California+Avenue+Santa+Monica+CA+90403",
    ceremonyDate: "Saturday, June 26, 2027",
    ceremonyNote: "Please arrive a little early for the ceremony.",
    receptionLabel: "Reception",
    receptionVenue: "Santa Monica Proper Hotel",
    receptionStreet: "700 Wilshire Boulevard",
    receptionCity: "Santa Monica, CA 90401",
    receptionTime: "4:00–10:00 PM",
    cocktailHour: "Cocktail hour: 4:00–5:00 PM",
    receptionMapLabel: "View directions ↗",
    receptionMapUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Monica+Proper+Hotel+700+Wilshire+Boulevard+Santa+Monica+CA+90401",
    receptionImageAlt: "Santa Monica Proper Hotel reception ballroom",
    receptionImageUrl: "https://www.properhotel.com/wp-content/uploads/2025/04/SMP_5-3_Ballroom_8-1024x614.jpg.webp",
    receptionImageLabel: "02 / The reception",
    scheduleLabel: "The evening",
    scheduleHeading: "A little glimpse of the day",
    schedule1Time: "12:30 PM",
    schedule1Title: "Guest arrival",
    schedule1Detail: "Find your seat at St. Monica before the ceremony begins.",
    schedule2Time: "1:00 PM",
    schedule2Title: "The ceremony",
    schedule2Detail: "Join us as we say yes to forever.",
    schedule3Time: "4:00 PM",
    schedule3Title: "Cocktail hour",
    schedule3Detail: "Drinks, small bites, and time to gather at Santa Monica Proper Hotel.",
    schedule4Time: "5:00 PM",
    schedule4Title: "Dinner & dancing",
    schedule4Detail: "An evening of good food, music, and celebration until 10:00 PM.",
    planningLabel: "For your weekend",
    planningHeading: "Make a little escape of it.",
    planningCopy: "We are gathering hotel, transportation, and local recommendations so your time in Los Angeles feels easy from arrival to farewell.",
    questionLinkLabel: "Ask a question",
    questionLinkUrl: "mailto:amberandalex@example.com?subject=Wedding%20question",
    losAngelesLinkLabel: "Explore Los Angeles",
    losAngelesLinkUrl: "https://www.google.com/maps/search/Los+Angeles,+California",
    zelleLinkLabel: "Zelle · (310) 867-9141",
    zelleLinkUrl: "tel:+13108679141",
    venmoLinkLabel: "Venmo · Amber · (562) 240-7587",
    venmoLinkUrl: "https://venmo.com/u/5622407587",
    rsvpLabel: "Please reply",
    rsvpHeading: "We hope you can be there.",
    rsvpCopy: "Kindly respond by May 1, 2027. A formal RSVP link will be included with your invitation.",
    rsvpButtonLabel: "Save your place",
    rsvpDialogHeading: "Who is joining us?",
    dialogCloseLabel: "Close",
    rsvpDialogCopy: "Enter your first and last name to save your place at the wedding.",
    rsvpFirstNameLabel: "First name",
    rsvpLastNameLabel: "Last name",
    rsvpSubmitLabel: "Confirm RSVP",
    rsvpSavingLabel: "Saving...",
    rsvpSuccessMessage: "You are on the list. We cannot wait to celebrate with you.",
    rsvpErrorMessage: "We could not save your RSVP just now. Please try again.",
    footerSignoff: "With love, Amber & Alex",
    footerLocation: "JUNE 26 · LOS ANGELES",
    loaderText: "Opening your invitation...",
  },
  bachelor: {
    heroEyebrow: "A / 2026",
    heroTopLabel: "Private weekend invite",
    title: "Alex's Bachelor Weekend",
    location: "Joshua Tree, California",
    dates: "September 4–6, 2026",
    heroKicker: "The groom's final fling",
    heroFooter: "The boys",
    scrollLabel: "Scroll for details ↓",
    introLabel: "You are invited",
    description: "A private weekend for Alex and the people who have been there for every chapter.",
    introCopy: "Pack light, bring your best stories, and get ready for a weekend that deserves its own group chat.",
    introSignoff: "See you there.",
    destinationLabel: "Where we are going",
    destinationNote: "The full address, arrival details, and room assignments will be shared in the group chat.",
    moodLabel: "The mood",
    moodHeading: "Desert air & good times",
    moodCopy: "A weekend of open roads, cold drinks, competitive games, and one very happy groom.",
    itineraryLabel: "On the agenda",
    itineraryHeading: "A weekend worth remembering.",
    activity1: "Arrival drinks & desert sunset",
    activity2: "Open-road day trip",
    activity3: "Dinner, games & stories",
    activity4: "Slow morning and farewell brunch",
    rsvpLabel: "RSVP",
    rsvpHeading: "Count yourself in.",
    rsvpCopy: "Let us know if you can make it so we can lock in the plans, rooms, and reservations.",
    rsvpButtonLabel: "RSVP now",
    footerSignoff: "Made for the memories.",
    footerCrew: "ALEX'S CREW",
    dialogLabel: "Alex's bachelor",
    dialogHeading: "Save your place.",
    dialogCopy: "Tell us who is joining the weekend.",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    submitLabel: "Confirm RSVP",
    savingLabel: "Saving...",
    successMessage: "You are on the list. We cannot wait to celebrate with you.",
    errorMessage: "We could not save that just now. Please try again.",
    loaderText: "Opening party details...",
  },
  bachelorette: {
    heroEyebrow: "B / 2026",
    heroTopLabel: "Private weekend invite",
    title: "Amber's Bachelorette Weekend",
    location: "Palm Springs, California",
    dates: "August 14–17, 2026",
    heroKicker: "The bride's last disco",
    heroFooter: "Girls only",
    scrollLabel: "Scroll for details ↓",
    introLabel: "You are invited",
    description: "A golden weekend for Amber and her favorite people, filled with sunshine, dancing, and a little bit of sparkle.",
    introCopy: "Pack light, bring your best stories, and get ready for a weekend that deserves its own group chat.",
    introSignoff: "See you there.",
    destinationLabel: "Where we are going",
    destinationNote: "The full address, arrival details, and room assignments will be shared in the group chat.",
    moodLabel: "The mood",
    moodHeading: "Pink skies & late nights",
    moodCopy: "Poolside afternoons, dinner reservations, matching pajamas, and dancing until we lose track of time.",
    itineraryLabel: "On the agenda",
    itineraryHeading: "A weekend worth remembering.",
    activity1: "Poolside welcome drinks",
    activity2: "Girls' dinner under the stars",
    activity3: "Matching pajamas & late-night laughs",
    activity4: "Brunch, photos and a final toast",
    rsvpLabel: "RSVP",
    rsvpHeading: "Count yourself in.",
    rsvpCopy: "Let us know if you can make it so we can lock in the plans, rooms, and reservations.",
    rsvpButtonLabel: "RSVP now",
    footerSignoff: "Made for the memories.",
    footerCrew: "AMBER'S CREW",
    dialogLabel: "Amber's bachelorette",
    dialogHeading: "Save your place.",
    dialogCopy: "Tell us who is joining the weekend.",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    submitLabel: "Confirm RSVP",
    savingLabel: "Saving...",
    successMessage: "You are on the list. We cannot wait to celebrate with you.",
    errorMessage: "We could not save that just now. Please try again.",
    loaderText: "Opening party details...",
  },
};